% Visualize the PSF stack
function visualizePSFstack(theOI, sampledWavelengths, psfRangeArcMin)
  hFig = figure(); clf;
  set(hFig,  'Color', [1 1 1], 'Position', [10 10 1800 900]);
  colsNum = 7;
  rowsNum = 3;
  subplotPosVectors = NicePlot.getSubPlotPosVectors(...
             'rowsNum', rowsNum, ...
             'colsNum', colsNum, ...
             'heightMargin',  0.08, ...
             'widthMargin',    0.02, ...
             'leftMargin',     0.05, ...
             'rightMargin',    0.00, ...
             'bottomMargin',   0.04, ...
             'topMargin',      0.02);

   wavelengthSupport = oiGet(theOI, 'wave');
   for k = 1:min([numel(sampledWavelengths) colsNum*rowsNum])

      [~,wIndex] = min(abs(wavelengthSupport-sampledWavelengths(k)));
      targetWavelength = wavelengthSupport(wIndex);

      row = floor((k-1)/colsNum)+1;
      col = mod(k-1,colsNum)+1;
      ax = subplot('Position', subplotPosVectors(row,col).v);
      visualizePSF(theOI, targetWavelength, psfRangeArcMin, ...
          'contourLevels', 0.1:0.1:0.9, ...
          'axesHandle', ax, ...
          'figureTitle', sprintf('%2.0f nm', targetWavelength), ...
          'fontSize', 14);
   end
   NicePlot.exportFigToPDF('PSFs.pdf', hFig, 300);
end